### PR TITLE
Reorg and add ReacttestKit

### PR DESCRIPTION
**Pull request by jjhuff**
This will require two changes in your projects: 
https://playful-software.github.io/test-components/index.js -> https://playful-software.github.io/test-components/TestKit/index.js
https://playful-software.github.io/react-components/dist/index.js -> https://playful-software.github.io/test-components/ReactTestKit/index.js

### CODE REVIEW

**Comment by bluedot74** [comment]
On `react-components` I'm able to develop against my local version by Importing from `http://127.0.0.1:8081/dist/index.js` while running `yarn serve`.
That doesn't seem to work here, looks like your building to ./build, but the `http-server` in ReactTestKit doesn't serve that directory (and apparently cannot serve directories above itself).
I've only just begun playing with these other repos, so I might be missing something obvious.

**Review by darrinm — APPROVED** [review]

**Comment by jjhuff** [comment]
> On `react-components` I'm able to develop against my local version by Importing from `http://127.0.0.1:8081/dist/index.js` while running `yarn serve`.
> That doesn't seem to work here, looks like your building to ./build, but the `http-server` in ReactTestKit doesn't serve that directory (and apparently cannot serve directories above itself).
> I've only just begun playing with these other repos, so I might be missing something obvious.

Does `yarn build; yarn serve` work if you run it within `ReactTestKit` ?

**Comment by bluedot74** [comment]
> Does `yarn build; yarn serve` work if you run it within `ReactTestKit` ?

Yes it does! Thanks

**Comment by jjhuff** [comment]
> > Does `yarn build; yarn serve` work if you run it within `ReactTestKit` ?
> 
> Yes it does! Thanks

Great. It might be handy to make a top-level `serve` target

**Pull request merged**
